repos:
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black-jupyter
        language_version: python3
        args:
          - --target-version=py310
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - xarray
