version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-22.9
  jobs:
    post_install:
      - jupyter nbconvert --execute --to notebook notebooks/*.ipynb
      - mv notebooks/*.nbconvert.ipynb doc/notebooks/

conda:
  environment: doc/requirements.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false # FIXME
