#!/usr/bin/env bash

set -o errexit

cd "$(dirname "$0")"
echo '# File generated by `pixi run export-docs-env`' > requirements.yml
pixi workspace export conda-environment >> requirements.yml
sed -i -E '/-e ./d' requirements.yml
