name: Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          use-mamba: true
          environment-file: ci/requirements-docs.yml
          activate-environment: pathfinder2e_stats-docs

      - name: Show conda options
        run: conda config --show

      - name: conda info
        run: conda info

      - name: conda list
        run: conda list

      - name: Build docs
        run: cd doc && make

      - uses: actions/upload-artifact@v4
        with:
          name: pathfinder2e_stats-docs
          path: build/html
