name: Wheels

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

# When this workflow is queued, automatically cancel any previous running
# or pending jobs from the same branch
concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full git history for setuptools_scm
          fetch-tags: true # Fetch tags for setuptools_scm

      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.53.0
          cache: true
          environments: dist

      - name: Build sdist and wheels
        run: pixi run dist

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install wheel
        run: pip install dist/*.whl

      - name: Smoke test
        working-directory: /tmp
        run: |
          cp ${{ github.workspace }}/smoke_test.py .
          python smoke_test.py

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
          if-no-files-found: error

  self-contained-test:
    name: self-contained test ${{ matrix.os }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest # x86-64
          - ubuntu-24.04-arm # ARM
          - macos-13 # x86-64
          - macos-latest # ARM
          - windows-latest # x86-64
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          merge-multiple: true # Don't use subdirectories

      - name: Unpack
        run: tar -xzvf pathfinder2e_stats-self-contained.tar.gz

      - name: Run self-contained smoke test (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: pathfinder2e_stats/run_self_contained.sh -e prod smoke-test

      - name: Run self-contained smoke test (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: pathfinder2e_stats\run_self_contained.ps1 -e prod smoke-test
